######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 20 20:45:08 2004
######################################################################

TEMPLATE = app
CONFIG -= qt
INCLUDEPATH += .
INCLUDEPATH += ..
LIBS += -ldl

# Input
HEADERS += UnitTestRunner.h
SOURCES += ConsoleTestRunner.cpp UnitTestRunner.cpp
