######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 20 20:41:45 2004
######################################################################

TEMPLATE = lib
CONFIG += dll
CONFIG -= qt
INCLUDEPATH += .
INCLUDEPATH += ..

# Input
HEADERS += Bank.h BankAccount.h
SOURCES += BankAccountTestCase.cpp BankTestCase.cpp TestSuite.cpp
