######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 20 10:32:22 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += ..
LIBS += -ldl

# Input
SOURCES += QtTestRunnerMain.cpp TestRunnerWidgetImpl.cpp TestCaseListViewItem.cpp TestListViewItem.cpp UnitTestRunner.cpp

FORMS +=  QtTestRunnerWidget.ui

